language: cpp
compiler: gcc

matrix:
  include:
    - os: linux
      dist: xenial
      addons:
        apt:
          packages:
            - cmake
            - libevent
            - libpcap


cache: # see https://docs.travis-ci.com/user/caching/
  - directories:
      - $HOME/.cache

install:
  # (fake) install dependencies (usually involves wget, configure, make, ...)
  # install into cache folder (build binaries+headers only, no sources and do NOT build there)
  - mkdir -p $HOME/.cache
# - touch $HOME/.cache/mydependency.so

script:
  - git submodule update --init
  - mkdir -p build
  - cd build
  - cmake ..
  - make
  - make test

after_success:
