version: '1.0.{build}'

image: Visual Studio 2017

platform:
  - x86
#   - x64

configuration:
  - Release
  - Debug

before_build:
  - cmd: |-
      mkdir build
      cd build
      cmake --version
      cmake .. -G "Visual Studio 15 2017" -DKCPP__ENABLE_TESTS=ON

build:
  project: build/kcpp.sln
  verbosity: minimal

test_script:
  - cd build/
  - ctest


skip_commits:
  message: /Update documentation.*/

