version: '1.0.{build}'

image:
  - Visual Studio 2017

#platform:
#  - x86
#   - x64

configuration:
  - Release
  - Debug

before_build:
  - cmd: |-
      dir C:\
      git submodule update --init
      mkdir build
      cd build
      cmake --version
      cmake .. -G "Visual Studio 15 2017" -DKCPP__ENABLE_TESTS=ON

build:
  project: build/kcpp.sln
  parallel: true
  verbosity: minimal

test_script:
  - ctest

cache:
  - C:/projects/kcpp/build
  - build

skip_commits:
  message: /Update documentation.*/

